FILES = io.f90 integral.f90 hf.f90 main.f90
LOC = .

FC = ifort
FCFLAGS = -O3 -mkl

#  ---------------------
GNU:    $(FILES)
	$(FC)  $(FCFLAGS) $(FILES)

#  ---------------------
	mv a.out lucifer
	

	
	
